[package]
name = "swift_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
phf = { version = "0.11", features = ["macros"] }
sha2 = "0.10"
base64 = "0.21"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"